version: "3.9"

networks:
  fc-frontend-network:
    name: forza-creations-frontend-network
  fc-backend-network:
    name: forza-creations-backend-network

services:
  proxy:
    container_name: proxy
    volumes:
      - ./docker/development/configs/proxy.conf:/etc/nginx/conf.d/forzacreations.conf:ro
    image: nginx
    depends_on:
      - frontend
    networks:
      - fc-frontend-network
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

  frontend:
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    build:
      context: .
      dockerfile: docker/development/build/frontend.Dockerfile
    networks:
      - fc-frontend-network
    expose:
      - 3000
    restart: unless-stopped